server:
  port: 8900

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
<<<<<<< HEAD
    url: jdbc:mariadb://localhost:3306/instagram_clone
=======
    url: jdbc:mariadb://localhost:3306/instagram
>>>>>>> d80e3810bdd39de7456f9c3d0e1a1d42e02771db
    username: root
    password: mariadb
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.example.instagramclone.domain
  mapper-locations: classpath:mapper/**/*.xml

logging:
  level:
    com:
      example:
        instagramclone: debug

file:
  upload:
    location: ${user.home}/instagram/uploads/